### ISSUE TITLE
Provide better errors if `svn` is missing

### ISSUE THREAD

**Issue by Geobert** [naufraghi/git-svn-clone-externals#2]
Hi, thank you for sharing this script but I have issue with it, running on Win 7 (I don't know if it is supposed to work on this OS)

```
Traceback (most recent call last):
  File "C:\Users\GQ185008\Documents\GIT\git_svn_clone_externals.py", line 241, in <module>
    run()
  File "C:\Users\GQ185008\Documents\GIT\git_svn_clone_externals.py", line 213, in run
    args, other_args = parser.parse_known_args()
  File "C:\Program Files (x86)\Python27\lib\argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files (x86)\Python27\lib\argparse.py", line 1942, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "C:\Program Files (x86)\Python27\lib\argparse.py", line 1898, in consume_positionals
    take_action(action, args)
  File "C:\Program Files (x86)\Python27\lib\argparse.py", line 1791, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "C:\Program Files (x86)\Python27\lib\argparse.py", line 2231, in _get_values
    value = self._get_value(action, arg_string)
  File "C:\Program Files (x86)\Python27\lib\argparse.py", line 2260, in _get_value
    result = type_func(arg_string)
  File "C:\Users\GQ185008\Documents\GIT\git_svn_clone_externals.py", line 171, in check_svn
    out = lsh(["svn", "info", path]).decode("utf8")
  File "C:\Users\GQ185008\Documents\GIT\git_svn_clone_externals.py", line 60, in _logged
    res = func(args, **kwargs)
  File "C:\Program Files (x86)\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Program Files (x86)\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Program Files (x86)\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by naufraghi** [comment]
Hi, do you have the subversion command line tool `svn.exe` in your PATH?

**Comment by Geobert** [comment]
Oh, I think this is it, only installed TortoiseSVN and it relies on libsvn I think. I'll try it tomorrow thanks!

**Comment by naufraghi** [comment]
TortoiseSVN has an installation option to install command line tools too, but their output is sometime non-standard. Another option is to install [SilkSvn](https://sliksvn.com/download/).

**Comment by Geobert** [comment]
I've installed svn cli option with tortoise and I go further but it's still failing (I'll open another issue)

But I've found another script that works for me https://github.com/danieldube/git-svn-tools/

**Comment by naufraghi** [comment]
Thanks, I should have fixed both issues, can you check please? This tool offers three recursive git-svn tools to help `dcommit` and `rebase`, have you tried them?

**Comment by Geobert** [comment]
indeed they are fixed, unfortunately, it seems the externals of my repo are not supported yet by your script:

```
Traceback (most recent call last):
  File "C:\Users\GQ185008\Documents\GIT\git_svn_clone_externals.py", line 254, in <module>
    run()
  File "C:\Users\GQ185008\Documents\GIT\git_svn_clone_externals.py", line 235, in run
    for rev, uri, path in normalize_externals(repo_root, svn_externals()):
  File "C:\Users\GQ185008\Documents\GIT\git_svn_clone_externals.py", line 169, in normalize_externals
    yield rev, extpath_join(repo_root, uri), os.path.normpath(os.path.join(root, path))
  File "C:\Users\GQ185008\Documents\GIT\git_svn_clone_externals.py", line 153, in extpath_join
    raise NotImplementedError
NotImplementedError
```

**Comment by naufraghi** [comment]
Can you post one example? In a new issue, if you can?
