### ISSUE TITLE
KeyError: 'LANG' on Win 7

### ISSUE THREAD

**Issue by Geobert** [naufraghi/git-svn-clone-externals#3]
After making sure svn.exe was present in PATH, I got this error now:

```
Traceback (most recent call last):
  File "C:\Users\GQ185008\Documents\GIT\git_svn_clone_externals.py", line 241, in <module>
    run()
  File "C:\Users\GQ185008\Documents\GIT\git_svn_clone_externals.py", line 217, in run
    with lang("C"):
  File "C:\Program Files (x86)\Python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Users\GQ185008\Documents\GIT\git_svn_clone_externals.py", line 41, in lang
    old_lang = os.environ["LANG"]
  File "C:\Program Files (x86)\Python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'LANG'
```

**Comment by naufraghi** [comment]
I was assuming the LANG variable as allways present, but that is not the case on windows.
